name: Compile artifacts when pushing to master.

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: rlespinasse/github-slug-action@master

    - name: Create version number
      run: echo ::set-env name=VERSION::draft_${{ env.GITHUB_SHA_SHORT }}
    
    - name: Build the Docker image that creates the RFC-PDFs
      run: docker build $GITHUB_WORKSPACE/build -t time-machine-project/publish_pdfs

    - name: Create the output directories
      run:  mkdir -p drafts
    
    - name: Create the draft PDFs
      run: docker run -e VERSION=${{ env.VERSION }} -v $GITHUB_WORKSPACE/files/drafts:/opt/input -v $GITHUB_WORKSPACE/drafts:/opt/output time-machine-project/publish_pdfs

    - name: Zip the draft PDFs
      run: zip -r -j drafts.zip drafts

    - uses: actions/upload-artifact@v1
      with:
        name: drafts
        path: drafts